//-------- Users endpoints --------//

### Get All Users
GET http://localhost:3306/users
Content-Type: application/json
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjA1MTkyMmNlLTZkMGQtNGJkZS1iMGEzLWQ2ZGRlMWJmMDQ3ZiIsImlhdCI6MTY3NjYzODM4MCwiZXhwIjoxNjc2NzI0NzgwfQ.aSQlqFtFHwFYoG2lRm89FPUvYlbt87tvlqxXxVCh9XQ

### Get Profile
GET http://localhost:3306/users/profile
Content-Type: application/json
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjA1MTkyMmNlLTZkMGQtNGJkZS1iMGEzLWQ2ZGRlMWJmMDQ3ZiIsImlhdCI6MTY3NjYzODM4MCwiZXhwIjoxNjc2NzI0NzgwfQ.aSQlqFtFHwFYoG2lRm89FPUvYlbt87tvlqxXxVCh9XQ

### Get User Profile
GET http://localhost:3306/users/profile/906b6835-e612-455e-bb5a-86d1607c9696
Content-Type: application/json
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjA1MTkyMmNlLTZkMGQtNGJkZS1iMGEzLWQ2ZGRlMWJmMDQ3ZiIsImlhdCI6MTY3NjYzODM4MCwiZXhwIjoxNjc2NzI0NzgwfQ.aSQlqFtFHwFYoG2lRm89FPUvYlbt87tvlqxXxVCh9XQ

### Sign Up
POST http://localhost:3306/users/signup
Content-Type: application/json

{
    "fullName": "Maria Silva",
    "email": "maria@gmail.com",
    "password": "123456"
}

### Login
POST http://localhost:3306/users/login
Content-Type: application/json

{
    "email": "gioivieira@gmail.com",
    "password": "123456"
}





//-------- Recipes endpoints --------//

### Get All Recipes
GET http://localhost:3306/recipes
Content-Type: application/json
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjA1MTkyMmNlLTZkMGQtNGJkZS1iMGEzLWQ2ZGRlMWJmMDQ3ZiIsImlhdCI6MTY3NjYzODM4MCwiZXhwIjoxNjc2NzI0NzgwfQ.aSQlqFtFHwFYoG2lRm89FPUvYlbt87tvlqxXxVCh9XQ

### Get Recipe
GET http://localhost:3306/recipes/:recipe_id
Content-Type: application/json
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjA1MTkyMmNlLTZkMGQtNGJkZS1iMGEzLWQ2ZGRlMWJmMDQ3ZiIsImlhdCI6MTY3NjYzODM4MCwiZXhwIjoxNjc2NzI0NzgwfQ.aSQlqFtFHwFYoG2lRm89FPUvYlbt87tvlqxXxVCh9XQ

### Create Recipe
POST http://localhost:3306/recipes/create
Content-Type: application/json
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjA1MTkyMmNlLTZkMGQtNGJkZS1iMGEzLWQ2ZGRlMWJmMDQ3ZiIsImlhdCI6MTY3NjYzODM4MCwiZXhwIjoxNjc2NzI0NzgwfQ.aSQlqFtFHwFYoG2lRm89FPUvYlbt87tvlqxXxVCh9XQ

{
    "title": "Feijoada",
    "description": "Eu amo."
}





//-------- Follows endpoints --------//

### Get All Follows
GET http://localhost:3306/follows
Content-Type: application/json
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjA1MTkyMmNlLTZkMGQtNGJkZS1iMGEzLWQ2ZGRlMWJmMDQ3ZiIsImlhdCI6MTY3NjYzODM4MCwiZXhwIjoxNjc2NzI0NzgwfQ.aSQlqFtFHwFYoG2lRm89FPUvYlbt87tvlqxXxVCh9XQ

### Follow User
POST http://localhost:3306/follows
Content-Type: application/json
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY2NWNlOGJlLTliNTAtNGE2NS1iZGYwLWUwNWNlYzVkZDVjMyIsImlhdCI6MTY3NjY0MDE5MSwiZXhwIjoxNjc2NzI2NTkxfQ.uh7m949_9rFm30pbZra9j9xoeA34_kD7HuDm0aDfVO0

{
    "userToFollowId": "665ce8be-9b50-4a65-bdf0-e05cec5dd5c3"
}

### Unfollow User
DELETE http://localhost:3306/follows/delete
Content-Type: application/json
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY2NWNlOGJlLTliNTAtNGE2NS1iZGYwLWUwNWNlYzVkZDVjMyIsImlhdCI6MTY3NjY0MDE5MSwiZXhwIjoxNjc2NzI2NTkxfQ.uh7m949_9rFm30pbZra9j9xoeA34_kD7HuDm0aDfVO0

{
    "userToFollowId": "665ce8be-9b50-4a65-bdf0-e05cec5dd5c3"
}